### ISSUE TITLE
[Question]: What is pseudo service?

### ISSUE THREAD

**Issue by renanbastos93** [nikoksr/notify#11]
Sorry guys, but I didn't understand if you really need this file: `[service/pseudo/pseudo.go](https://github.com/nikoksr/notify/blob/main/service/pseudo/pseudo.go)`

**Comment by KrishanBhalla** [comment]
I'm largely in agreement here - the avoiding of nil reference errors is better handled directly rather than having this "pseudo"

**Comment by nikoksr** [comment]
Hey @renanbastos93 and @KrishanBhalla, appreciate your efforts and I totally agree with both of you. The pseudo service is a relic of the past and we have even implemented a regular nil check. So you are right, the service is completely obsolete.

I will look over #13 and close this issue afterwards!

**Comment by nikoksr** [comment]
Closed in #13
