### ISSUE TITLE
 feat(service): Add FCM service

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/notify#113]
**Is your feature request related to a problem? Please describe.**

Missing support for [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging).

**Describe the solution you'd like**

Implement a [notification service](https://github.com/nikoksr/notify/tree/main/service) and use existing services such as [WhatsApp](https://github.com/nikoksr/notify/tree/main/service/whatsapp) as a guide for implementation. At the time writing this, [appleboy/go-fcm](https://github.com/appleboy/go-fcm) seems to be the best client library for our service.

**Comment by fjloyola** [comment]
hey @nikoksr 
 can I pick this up?

**Comment by svaloumas** [comment]
Hello @nikoksr, can I give this a try?

**Comment by nikoksr** [comment]
@svaloumas sure thing, thanks! Let me know if you need any help.

**Comment by nikoksr** [comment]
Closed by @svaloumas in #272.
