### ISSUE TITLE
feat(service): Add Viber service

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/notify#114]
**Is your feature request related to a problem? Please describe.**

Missing support for [Viber](https://www.viber.com).

**Describe the solution you'd like**

Implement a [notification service](https://github.com/nikoksr/notify/tree/main/service) and use existing services such as [WhatsApp](https://github.com/nikoksr/notify/tree/main/service/whatsapp) as a guide for implementation. At the time writing this, [mileusna/viber](https://github.com/mileusna/viber) seems to be the best client library for our service.

**Comment by stavdav143** [comment]
hey Niko, 
can I give this a go?
Grüße aus Zürich

**Comment by irfansofyana** [comment]
Hi @nikoksr it looks like this issue has been exist for some time, may I try to work on this?

**Comment by nikoksr** [comment]
Hey @irfansofyana, thanks for taking this on. Sure, go ahead, I'll assign the issue to you.

**Comment by irfansofyana** [comment]
Hi @nikoksr kindly help your review on this PR: https://github.com/nikoksr/notify/pull/415, thank you 🙏

**Comment by irfansofyana** [comment]
Also, @nikoksr, will it be possible to make this issue added to hacktoberfest by adding `hacktoberfest` label? If it can, that would be very great!

**Comment by nikoksr** [comment]
Closed in #415.
