### ISSUE TITLE
[INTERFACES] maybe we can to use interfaces on project

### ISSUE THREAD

**Issue by renanbastos93** [nikoksr/notify#12]
I believe that we can create an interface to subscribe to all services. However, we will guarantee integrity in all methods.
e.g
```go
type IServices interface{
        New() interface{}
        Send(string, string) error
}

type Telegram struct {
        IServices // is obrigatory to create methods New and Send
	client   *tgbotapi.BotAPI
	listener *tgbotapi.BotAPI
	chatIDs  []int64
}

func (t *Telegram) New() *Telegram {
	return &Telegram{}
}

func (t *Telegram) Send(param1, param2 string) error{
	return nill
}

```

see ya

**Comment by KrishanBhalla** [comment]
The "Notifier" interface already exists no? And New does not have such a standard form (see the mail.go)

**Comment by nikoksr** [comment]
Yes, I agree with @KrishanBhalla here. The notifier interface serves this purpose. I'm still very grateful to you for looking for improvements, @renanbastos93. I'll close the issue, but feel free to continue the discussion.
