### ISSUE TITLE
Feat - Go Mail

### ISSUE THREAD

**Issue by ainsleyclark** [nikoksr/notify#279]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be great to see the use of Go Mail used in this project. [https://github.com/ainsleyclark/go-mail](https://github.com/ainsleyclark/go-mail)
I think this will add SparkPost, Postal and Postmark support for free with no external dependencies. 

I've noticed the go.mod file is quite large and this maybe a great opportunity to make it smaller by using the Mail drivers in the package outlined. All drivers in the Go Mail package use the std lib http client.

**Describe alternatives you've considered**
N/A

**Comment by KaptinLin** [comment]
it seems good

**Comment by nikoksr** [comment]
@ainsleyclark thanks for bringing in that idea. I checked your project and like what you've done. 

I don't necessarily see a problem with a "big" go.mod file especially in a project like `Notify`. Notify tries to support as many services as possible and thus it somewhat lies in its nature to be dependant on a lot of external services and libraries. Maybe you can explain to me where you see the problem with the list of dependencies; it's very possible that I'm overseeing something here!

The problem with using your solution is, that up to six services would be relying on a single library. With the current way of things six services would be distributed across six libraries. To me, this minimizes the potential for a big functionality fallout. Six services would depend solely on your work and your reliability.

Please let me know, if you see something that I don't! Appreicate your input nonetheless.
