### ISSUE TITLE
 feat(service): Add WeChat service

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/notify#28]
**Is your feature request related to a problem? Please describe.**

Missing support for the popular social network platform [WeChat](https://www.wechat.com/).

**Describe the solution you'd like**

Implement a [notification service](https://github.com/nikoksr/notify/tree/main/service) like we already did for [Telegram](https://github.com/nikoksr/notify/blob/main/service/telegram/telegram.go) etc. At the time writing this [fideism/golang-wechat](https://github.com/fideism/golang-wechat) seems to be our best option for implementing it.

**Comment by gtourkas** [comment]
@nikoksr can i pick this up ?

**Comment by gtourkas** [comment]
#68

**Comment by nikoksr** [comment]
Closed in #68.
