### ISSUE TITLE
feat(service): Add WhatsApp service

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/notify#3]
**Is your feature request related to a problem? Please describe.**

Missing support for the popular messaging platform [WhatsApp](https://www.whatsapp.com).

**Describe the solution you'd like**

Implement a [notification service](https://github.com/nikoksr/notify/tree/main/service) like we already did for [Telegram](https://github.com/nikoksr/notify/blob/main/service/telegram/telegram.go) etc. At the time writing this [Rhymen/go-whatsapp](https://github.com/Rhymen/go-whatsapp) seems to be our best option for implementing it.

**Comment by checkaayush** [comment]
Hi @nikoksr, I'd like to give this a shot.

**Comment by nikoksr** [comment]
@checkaayush, hope things are going well. Let us know if you need any help!
