### ISSUE TITLE
feat(examples): Give more examples

### ISSUE THREAD

**Issue by catwithtudou** [nikoksr/notify#34]
**Is your feature request related to a problem? Please describe.**

Hi! There is a problem that I don't know how to use it when I ready to use the email service.

**Describe the solution you'd like**

So we can give the more examples or docs that make more people like me know how to use it. It's very helpful.

**Comment by KrishanBhalla** [comment]
In absence of documentation, I hope this helps. 

## Sending emails
```go

/ The notifier we will send our messages to
notifier := notify.New()

// You find out what is needed by looking at the "New" method in the relevant package - i.e. service/mail
// For many services (slack, telegram) this is a single API token 
mailService,  _ := mail.New(senderAddress, smtpHostAddress)

// Passing  the receiving email addresses
mailService.AddReceivers("ex@mple.com", "my@email.com")

notifier.UseServices(mailService)

// Send a message
_ = notifier.Send(
	**_"Email Subject",
	"The body of the email",_**
)

```



## Sending both emails and slack messages
```go

// Initialise 
notifier := notify.New()
// Note for slack you must set up a slack app - please see services/slack/usage.md
slackService,  _ := slack.New(apiToken)
mailService,  _ := mail.New(senderAddress, smtpHostAddress)



// Add receivers
mailService.AddReceivers("ex@mple.com", "my@email.com")
mailService.AddReceivers("channel1", "channel2")

// add services to notifier
notifier.UseServices(mailService, slackService)

// Send a message
_ = notifier.Send(
	**_"Email Subject",
	"The body of the email",_**
)

```

**Comment by chanioxaris** [comment]
@KrishanBhalla just to correct a typo in your examples, the line `mailService.AddReceivers("channel1", "channel2")` should be `slackService.AddReceivers("channel1", "channel2")`

**Comment by catwithtudou** [comment]
Thanks! It's useful!

**Comment by KrishanBhalla** [comment]
> @KrishanBhalla just to correct a typo in your example, the line `mailService.AddReceivers("channel1", "channel2")` must be `slackService.AddReceivers("channel1", "channel2")`

Thanks! Good catch
