### ISSUE TITLE
feat(service): Add SendGrid service

### ISSUE THREAD

**Issue by chanioxaris** [nikoksr/notify#38]
**Is your feature request related to a problem? Please describe.**

Missing support for the popular email service platform [SendGrid](https://sendgrid.com/).

**Describe the solution you'd like**

Implement a notification service like already exists for Telegram etc. At the time writing the official Golang SDK [sendgrid/sendgrid-go](https://github.com/sendgrid/sendgrid-go) seems to be our best option for implementing it.

**Describe alternatives you've considered**

Should we place the implementation under the `mail` package with the following constructor `mail.NewSendGrid(...)` or into a new separate package `sendgrid`?

**Comment by nikoksr** [comment]
Hi! In the case of _Pushbullet_ we have handled it so that the _SMS_ service was packed into the [pushbullet package](https://github.com/nikoksr/notify/tree/main/service/pushbullet). So I would suggest that we keep that and put _SendGrid_'s email support in the _SendGrind_ package.

**Comment by chanioxaris** [comment]
Great i have created the PR #40 with the implementation

**Comment by nikoksr** [comment]
Closed in #40

**Comment by nikoksr** [comment]
Closed in #40
