### ISSUE TITLE
feat(service): Add Mailgun service

### ISSUE THREAD

**Issue by chanioxaris** [nikoksr/notify#41]
**Is your feature request related to a problem? Please describe.**

Missing support for the popular email service platform [Mailgun](https://www.mailgun.com/).

**Describe the solution you'd like**

Implement a notification service like already exists for Telegram etc. At the time writing the official Golang SDK [mailgun/mailgun-go](https://github.com/mailgun/mailgun-go) seems to be our best option for implementing it.

**Comment by chanioxaris** [comment]
Created a PR #42 with the proposed implementation

**Comment by nikoksr** [comment]
Closed in #42
