### ISSUE TITLE
[BUG] Syslog test seems to fail under WSL

### ISSUE THREAD

**Issue by irfansofyana** [nikoksr/notify#416]
**Describe the bug**

There is an error in the Syslog test that causing error when running `make test`

**To Reproduce**

1. Execute command `make test`

**Expected behavior**

Syslog test should be passed and all tests will be passed

**Screenshots**
![image](https://user-images.githubusercontent.com/33191443/194714025-f7e3a550-f3a5-444e-bb8c-90e531ed06e0.png)

**System**

 - OS: Ubuntu 20 on WSL 2.0
 - Go Version: 1.19
 - Library Version: [e.g. 0.19.2]

**Additional context**

**Comment by nikoksr** [comment]
@irfansofyana thanks for the report. I suspect this is caused by WSL, since the test fails in no other environment. I don't have a Windows machine ready for testing tho. Either I set one up in the coming days or someone else might confirm that WSL is the error cause.

**Comment by irfansofyana** [comment]
I see, thanks for the info @nikoksr I agree that it might be causing some connection issues on WSL. If I have time, I will try to dig further on this issue

**Comment by nikoksr** [comment]
@irfansofyana that would be greatly appreciated!

**Comment by nikoksr** [comment]
@irfansofyana any updates on this yet?

**Comment by irfansofyana** [comment]
@nikoksr hey apologize, I haven't got time to dig further on this issue. Will try to debug it on the weekend!

**Comment by nikoksr** [comment]
@irfansofyana no, no worries! Just checking. Nice, that would be greatly appreciated! Let me know if there's anything I can help you with.

**Comment by joshm91** [comment]
@irfansofyana Can you try running `service rsyslog status` to see if rsyslogd is running? If it's not, try running `service rsyslog start` and then re-running the test suite.

Ref: https://answers.microsoft.com/en-us/windows/forum/all/location-of-syslog-file-in-windows-10-ubuntu-bash/ae40a2d2-005e-4130-b830-d90e768e6fb5

**Comment by nikoksr** [comment]
Closing this as stale since no further reports have reached us. Please reopen if it's still an active issue.
