### ISSUE TITLE
[BUG] Incorrect Link in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by SarojWasti** [nikoksr/notify#423]
**Describe the bug**

The link to Mozilla's code of conduct Enforcement ladder under the [Attribution](https://github.com/nikoksr/notify/blob/main/CODE_OF_CONDUCT.md#attribution) section just redirects to mozilla inclusion repo.

**Comment by SarojWasti** [comment]
@nikoksr Can you assign it to me if this issue gets considered?

**Comment by nikoksr** [comment]
@SarojWasti good catch. Sure, we'd appreciate you fixing this!
