### ISSUE TITLE
feat(service): Add Amazon SES service 

### ISSUE THREAD

**Issue by chanioxaris** [nikoksr/notify#44]
**Is your feature request related to a problem? Please describe.**

Missing support for the popular Amazon service [Simple Email Service (SES)](https://aws.amazon.com/ses/).

**Describe the solution you'd like**

Implement a notification service like already exists for Telegram etc. At the time writing the official Amazon Golang SDK [aws/aws-sdk-go](https://github.com/aws/aws-sdk-go) is the best option for implementing it.

**Describe alternatives you've considered**

What is the preferred package name for this service. Should i named it **amazonses** or is there any other suggestion?

**Comment by chanioxaris** [comment]
Created PR #47 with the implementation

**Comment by nikoksr** [comment]
Closed in d0177255365da445fb29d02aa2aed81eac09a139.
