### ISSUE TITLE
feat(service): Add Gitter service

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/notify#458]
**Describe the missing service. Please provide useful links.**

Add new service for [Gitter](https://gitter.im/). API docs can be found [here](https://developer.gitter.im/docs/rest-api).

**Comment by deoooo** [comment]
The API docs link is not accessible, please correct it. @nikoksr

**Comment by nikoksr** [comment]
Appears like gitter is now using matrix, which we already support. Closing.
