### ISSUE TITLE
Discord Webhooks

### ISSUE THREAD

**Issue by gaurishhs** [nikoksr/notify#554]
**Is your feature request related to a problem? Please describe.**

Discord already has Webhooks for notifications, It makes no sense to use gateway (bot sessions) to send notifications

**Describe the solution you'd like**

Instead of using `discordgo` Use simple HTTP post requests to post to a discord webhook

**Describe alternatives you've considered**

Shoutrrr uses discord webhooks https://containrrr.dev/shoutrrr/0.7/services/discord/

**Additional context**

I'm willing to make a PR for this. 
[Discord Webhook Documentation](https://discord.com/developers/docs/resources/webhook)

**Comment by gaurishhs** [comment]
Ah yes, I'm sorry. I was just taking a first look at this library (thanks for this its really useful) and after taking a look at the http service i don't think so theres a need for seperate function since this will increase the size. I made the webhook thing functional by utilising the Discord Webhook API and the http service with a custom `BuildPayload` function

**Comment by nikoksr** [comment]
@gaurishhs that's great to hear! Did the HTTP servce work well for you?

I'm still inclined of adding this to the library as it reuses existing code, meaning no additional logic we have to maintain and at the same time makes the library or the discord service in particular more accessible.

**Comment by gaurishhs** [comment]
Yes, It worked for me
