### ISSUE TITLE
feat(service): Add TextMagic service 

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/notify#82]
**Is your feature request related to a problem? Please describe.**

Missing support for the business level sms messaging platform [TextMagic](https://www.textmagic.com/).

**Describe the solution you'd like**

Implement a [notification service](https://github.com/nikoksr/notify/tree/main/service) like we already did for [Plivo](https://github.com/nikoksr/notify/tree/main/service/plivo) etc. At the time writing this [textmagic/textmagic-rest-go-v2](https://github.com/textmagic/textmagic-rest-go-v2) seems to be our best option for implementing it. Further note the [offical Go usage examples](https://docs.textmagic.com/#section/Go) by TextMagic.

**Comment by himsngh** [comment]
Hey, I would like to take this issue.
